# Generated by Django 5.1.2 on 2024-11-09 18:52

import django.db.models.deletion
import django.utils.timezone
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_category_alter_product_vendor_color_and_more'),
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'managed': True, 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelTable(
            name='gallery',
            table='',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total of Product price * Product Quantity', max_digits=8, null=True)),
                ('shipping_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('tax_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('initiated', 'Initiated'), ('failed', 'failed'), ('refunding', 'refunding'), ('unpaid', 'unpaid'), ('expired', 'expired')], default='initiated', max_length=100)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Partially Fulfilled', 'Partially Fulfilled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('initial_total', models.DecimalField(decimal_places=2, help_text='The original total before discounts', max_digits=12)),
                ('saved', models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved by customer', max_digits=12, null=True)),
                ('full_name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('mobile', models.CharField(max_length=1000)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ManyToManyField(blank=True, related_name='orders', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['-datetime_created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='Total of Product price * Product Quantity', max_digits=12)),
                ('shipping_amount', models.DecimalField(decimal_places=2, help_text='Estimated Shipping Fee = shipping_fee * total', max_digits=12)),
                ('tax_fee', models.DecimalField(decimal_places=2, help_text='Estimated Vat based on delivery country = tax_rate * (total + shipping)', max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Estimated Service Fee = service_fee * total (paid by buyer to platform)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, help_text='Grand Total of all amount listed above', max_digits=12)),
                ('initial_total', models.DecimalField(decimal_places=2, help_text='Grand Total of all amount listed above before discount', max_digits=12)),
                ('saved', models.DecimalField(blank=True, decimal_places=2, help_text='Amount saved by customer', max_digits=12, null=True)),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendor.vendor')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'ordering': ['-datetime_created'],
            },
        ),
    ]
