# Generated by Django 5.1.2 on 2024-11-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('rate', models.IntegerField(default=10, help_text='Numbers are added here in percentage e.g 10%')),
                ('active', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
                'db_table': '',
                'ordering': ['country'],
                'managed': True,
            },
        ),
    ]
