# Generated by Django 5.1.2 on 2025-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_service_fee_alter_order_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='initial_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The original total before discounts', max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount saved by customer', max_digits=12, null=True),
        ),
    ]
