# Generated by Django 5.1.2 on 2025-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_initial_total_alter_order_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='coupon',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
